name: .NET Core CI for Service.Catalog

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore Service.Catalog.sln

    - name: Build
      run: dotnet build Service.Catalog.sln --no-restore

    - name: Run Unit Tests
      run: dotnet test Service.Catalog.UnitTests/Service.Catalog.UnitTests.csproj --no-restore --verbosity normal